"""
Web App Metadata Crawler Service

Uses Playwright (headless Chromium) to crawl the target web application and
extract live DOM metadata — routes, buttons, forms, headings, ARIA labels,
navigation links — so the AI can generate Playwright test steps that reference
REAL element identifiers instead of hallucinated ones.

Key design decisions:
  - Reuses `metadata_normalized` table (entity_type="webpage") for caching.
  - Optionally loads a stored session (storageState.json) so authenticated pages
    are crawled correctly (reuses WebPlaywrightService session files).
  - Limits crawl to `max_pages` to keep generation latency acceptable.
  - Zero impact on Salesforce paths — only called from a strict
    `if project.category == "webapp"` guard in tests.py.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from urllib.parse import urljoin, urlparse

from playwright.async_api import async_playwright, BrowserContext, Page

logger = logging.getLogger(__name__)


# ── Data Structures ──────────────────────────────────────────────────


@dataclass
class ElementInfo:
    role: str = ""          # button / link / textbox / combobox / checkbox …
    name: str = ""          # accessible name (aria-label, placeholder, text)
    tag: str = ""           # raw HTML tag
    locator_type: str = ""  # role | label | placeholder | testid | css
    locator: str = ""       # ready-to-use locator string for the AI
    required: bool = False  # whether the field is mandatory


@dataclass
class PageMetadata:
    url: str = ""
    path: str = ""          # relative path e.g. "/login"
    title: str = ""
    headings: List[str] = field(default_factory=list)   # h1–h3 text
    buttons: List[ElementInfo] = field(default_factory=list)
    links: List[ElementInfo] = field(default_factory=list)
    inputs: List[ElementInfo] = field(default_factory=list)
    selects: List[ElementInfo] = field(default_factory=list)
    testids: List[str] = field(default_factory=list)    # data-testid values


@dataclass
class WebAppMetadata:
    base_url: str = ""
    pages: List[PageMetadata] = field(default_factory=list)


# ── Crawler ──────────────────────────────────────────────────────────


class WebCrawlerService:
    """Playwright-based crawler that extracts DOM metadata from a web app."""

    # ── Public API ───────────────────────────────────────────────────

    @staticmethod
    async def crawl(
        base_url: str,
        max_pages: int = 8,
        auth_session_path: Optional[str] = None,
        extra_paths: Optional[List[str]] = None,
    ) -> WebAppMetadata:
        """
        Crawl the web app starting from `base_url`.

        Args:
            base_url:          Root URL of the app (e.g. http://localhost:3002)
            max_pages:         Maximum number of pages to visit (default 8)
            auth_session_path: Path to a Playwright storageState JSON file
                               (generated by WebPlaywrightService auto-login).
                               If provided, the crawl runs as an authenticated user.
            extra_paths:       Additional relative paths to visit
                               (e.g. ["/dashboard", "/projects"]).

        Returns:
            WebAppMetadata containing metadata for every page visited.
        """
        metadata = WebAppMetadata(base_url=base_url.rstrip("/"))
        visited: set[str] = set()
        queue: List[str] = [base_url.rstrip("/") + "/"]

        if extra_paths:
            for p in extra_paths:
                queue.append(base_url.rstrip("/") + "/" + p.lstrip("/"))

        async def _run():
            async with async_playwright() as pw:
                browser = await pw.chromium.launch(headless=True)
                context = await _make_context(browser, auth_session_path)
                page = await context.new_page()
                page.set_default_timeout(20_000)
                page.set_default_navigation_timeout(30_000)

                pages_crawled = 0
                while queue and pages_crawled < max_pages:
                    url = queue.pop(0)
                    norm = _normalize_url(url, base_url)
                    if not norm or norm in visited:
                        continue
                    visited.add(norm)

                    try:
                        page_meta = await WebCrawlerService._visit_page(
                            page, norm, base_url
                        )
                        if page_meta:
                            metadata.pages.append(page_meta)
                            pages_crawled += 1
                            logger.info(
                                f"[CRAWLER] Crawled ({pages_crawled}/{max_pages}): {norm}"
                            )

                            # Enqueue discovered internal links
                            for link in page_meta.links:
                                candidate = link.locator or ""
                                if candidate.startswith(base_url):
                                    cn = _normalize_url(candidate, base_url)
                                    if cn and cn not in visited:
                                        queue.append(cn)
                    except Exception as e:
                        logger.warning(f"[CRAWLER] Failed to crawl {norm}: {e}")

                await browser.close()

        try:
            await asyncio.wait_for(_run(), timeout=120)
        except asyncio.TimeoutError:
            logger.warning("[CRAWLER] Crawl timed out after 120s")

        logger.info(f"[CRAWLER] Finished. Crawled {len(metadata.pages)} pages.")
        return metadata

    @staticmethod
    async def crawl_single_page(
        url: str,
        base_url: str,
        auth_session_path: Optional[str] = None,
    ) -> Optional[PageMetadata]:
        """Crawl exactly one page and return its metadata."""
        result: Optional[PageMetadata] = None

        async def _run():
            nonlocal result
            async with async_playwright() as pw:
                browser = await pw.chromium.launch(headless=True)
                context = await _make_context(browser, auth_session_path)
                page = await context.new_page()
                page.set_default_timeout(20_000)
                page.set_default_navigation_timeout(30_000)
                result = await WebCrawlerService._visit_page(page, url, base_url)
                await browser.close()

        try:
            await asyncio.wait_for(_run(), timeout=60)
        except asyncio.TimeoutError:
            logger.warning(f"[CRAWLER] Single-page crawl timed out for {url}")

        return result

    @staticmethod
    async def crawl_creation_form(
        base_url: str,
        object_name: str,
        auth_session_path: Optional[str] = None,
        credentials: Optional[Dict[str, str]] = None,
    ) -> Optional[PageMetadata]:
        """
        Targeted deep crawl: navigate through button clicks to reach a record
        creation form and extract its form fields + mandatory markers.

        If credentials are provided and no session exists, performs auto-login
        using common form patterns (email/username + password + submit).
        """
        result: Optional[PageMetadata] = None
        obj_lower = object_name.lower().strip()
        obj_plural = obj_lower + "s" if not obj_lower.endswith("s") else obj_lower
        obj_title = object_name.strip().title()
        obj_plural_title = obj_plural.title()

        logger.info(f"[CRAWLER] Deep crawl: targeting creation form for '{obj_title}'")

        async def _run():
            nonlocal result
            async with async_playwright() as pw:
                browser = await pw.chromium.launch(headless=True)
                context = await _make_context(browser, auth_session_path)
                page = await context.new_page()
                page.set_default_timeout(20_000)
                page.set_default_navigation_timeout(30_000)

                # Step 1: Navigate to app
                try:
                    await page.goto(base_url, wait_until="domcontentloaded", timeout=25_000)
                    try:
                        await page.wait_for_load_state("networkidle", timeout=5_000)
                    except Exception:
                        await asyncio.sleep(1)
                    logger.info(f"[CRAWLER] Deep crawl: loaded {base_url}")
                except Exception as e:
                    logger.warning(f"[CRAWLER] Deep crawl: failed to load {base_url}: {e}")
                    await browser.close()
                    return

                # Step 1b: Auto-login if on a login page
                # Detect login page by checking for visible password field
                try:
                    pwd_field = page.locator('input[type="password"]')
                    if await pwd_field.count() > 0 and await pwd_field.first.is_visible():
                        if credentials and credentials.get("username") and credentials.get("password"):
                            logger.info("[CRAWLER] Deep crawl: login page detected, performing login")
                            # Find and fill username/email field
                            for selector in [
                                'input[type="email"]',
                                'input[name="username"]', 'input[name="email"]',
                                'input[name="user"]', 'input[name="login"]',
                                'input[id="username"]', 'input[id="email"]',
                                'input[type="text"]',
                            ]:
                                try:
                                    user_field = page.locator(selector).first
                                    if await user_field.is_visible(timeout=1000):
                                        await user_field.fill(credentials["username"])
                                        logger.info(f"[CRAWLER] Deep crawl: filled username via {selector}")
                                        break
                                except Exception:
                                    continue
                            # Fill password
                            await pwd_field.first.fill(credentials["password"])
                            # Click login/submit button
                            for btn_name in ["Log In", "Login", "Sign In", "Submit", "Log in", "Sign in"]:
                                try:
                                    btn = page.get_by_role("button", name=btn_name, exact=False)
                                    if await btn.count() > 0:
                                        await btn.first.click(timeout=5_000)
                                        logger.info(f"[CRAWLER] Deep crawl: clicked '{btn_name}' button")
                                        break
                                except Exception:
                                    continue
                            # Wait for login to complete
                            await asyncio.sleep(3)
                            try:
                                await page.wait_for_load_state("networkidle", timeout=10_000)
                            except Exception:
                                pass
                            # Save session for future use
                            if auth_session_path:
                                try:
                                    import os as _os
                                    _os.makedirs(_os.path.dirname(auth_session_path), exist_ok=True)
                                    await context.storage_state(path=auth_session_path)
                                    logger.info(f"[CRAWLER] Deep crawl: saved session to {auth_session_path}")
                                except Exception:
                                    pass
                            logger.info(f"[CRAWLER] Deep crawl: login complete, now at {page.url}")
                        else:
                            logger.warning("[CRAWLER] Deep crawl: login page detected but no credentials provided")
                            await browser.close()
                            return
                except Exception as login_err:
                    logger.debug(f"[CRAWLER] Deep crawl: login check error: {login_err}")

                # Step 2: Click object navigation button
                nav_clicked = False
                # Try multiple name variants: "Contacts", "contacts", "CONTACTS"
                for nav_name in [obj_plural_title, obj_title, obj_plural, obj_lower]:
                    try:
                        nav_btn = page.get_by_role("button", name=nav_name, exact=False)
                        if await nav_btn.count() > 0:
                            await nav_btn.first.click(timeout=10_000)
                            nav_clicked = True
                            logger.info(f"[CRAWLER] Deep crawl: clicked nav button '{nav_name}'")
                            break
                    except Exception:
                        continue
                    # Also try links
                    try:
                        nav_link = page.get_by_role("link", name=nav_name, exact=False)
                        if await nav_link.count() > 0:
                            await nav_link.first.click(timeout=10_000)
                            nav_clicked = True
                            logger.info(f"[CRAWLER] Deep crawl: clicked nav link '{nav_name}'")
                            break
                    except Exception:
                        continue

                if not nav_clicked:
                    # Try direct URL navigation as fallback
                    try:
                        await page.goto(
                            f"{base_url}/{obj_plural}",
                            wait_until="domcontentloaded", timeout=15_000
                        )
                        nav_clicked = True
                        logger.info(f"[CRAWLER] Deep crawl: navigated to /{obj_plural}")
                    except Exception:
                        logger.warning(f"[CRAWLER] Deep crawl: could not find nav for '{obj_title}'")
                        await browser.close()
                        return

                # Wait for page to settle after navigation
                await asyncio.sleep(3)
                try:
                    await page.wait_for_load_state("networkidle", timeout=8_000)
                except Exception:
                    pass

                # Step 3: Click "New [Object]" button
                new_clicked = False
                new_variants = [
                    f"New {obj_title}",
                    f"Create {obj_title}",
                    f"Add {obj_title}",
                    f"New",
                    f"Create",
                    f"Add New",
                ]
                for new_name in new_variants:
                    try:
                        new_btn = page.get_by_role("button", name=new_name, exact=False)
                        if await new_btn.count() > 0:
                            await new_btn.first.click(timeout=10_000)
                            new_clicked = True
                            logger.info(f"[CRAWLER] Deep crawl: clicked '{new_name}' button")
                            break
                    except Exception:
                        continue
                    try:
                        new_link = page.get_by_role("link", name=new_name, exact=False)
                        if await new_link.count() > 0:
                            await new_link.first.click(timeout=10_000)
                            new_clicked = True
                            logger.info(f"[CRAWLER] Deep crawl: clicked '{new_name}' link")
                            break
                    except Exception:
                        continue

                if not new_clicked:
                    logger.warning(f"[CRAWLER] Deep crawl: no 'New {obj_title}' button found")
                    # Still extract the list page metadata
                    result = await WebCrawlerService._visit_page(
                        page, page.url, base_url
                    )
                    await browser.close()
                    return

                # Step 4: Wait for the creation form to load
                await asyncio.sleep(3)
                try:
                    await page.wait_for_load_state("networkidle", timeout=8_000)
                except Exception:
                    await asyncio.sleep(1)

                # Step 5: Extract form metadata from the creation page
                logger.info(f"[CRAWLER] Deep crawl: extracting form metadata from {page.url}")
                result = await WebCrawlerService._visit_page(
                    page, page.url, base_url
                )
                if result:
                    result.path = f"/{obj_plural}/new"
                    logger.info(
                        f"[CRAWLER] Deep crawl: found {len(result.inputs)} inputs, "
                        f"{len(result.buttons)} buttons, {len(result.selects)} selects"
                    )
                    # Log required fields
                    req_fields = [inp for inp in result.inputs if inp.required]
                    if req_fields:
                        logger.info(
                            f"[CRAWLER] Deep crawl: {len(req_fields)} REQUIRED fields: "
                            f"{[f.name for f in req_fields]}"
                        )

                await browser.close()

        try:
            await asyncio.wait_for(_run(), timeout=90)
        except asyncio.TimeoutError:
            logger.warning(f"[CRAWLER] Deep crawl timed out for '{obj_title}'")

        return result

    @staticmethod
    def build_context_string(metadata: WebAppMetadata) -> str:
        """
        Convert WebAppMetadata into a compact, LLM-friendly text string.

        The output is injected into the AI system prompt so the model knows
        exactly which elements exist on each page.
        """
        if not metadata.pages:
            return "(No pages crawled)"

        lines: List[str] = [
            f"=== WEB APP METADATA (crawled from {metadata.base_url}) ===",
            f"Total pages crawled: {len(metadata.pages)}",
            "",
        ]

        for pm in metadata.pages:
            lines.append(f"--- PAGE: {pm.path or pm.url} ---")
            if pm.title:
                lines.append(f"  Title: {pm.title}")
            if pm.headings:
                lines.append(f"  Headings: {', '.join(pm.headings[:5])}")

            if pm.buttons:
                lines.append("  Buttons (use locator_type='role'):")
                for btn in pm.buttons[:15]:
                    lines.append(f"    • {btn.locator}  [{btn.name}]")

            if pm.links:
                lines.append("  Links (use locator_type='role'):")
                for lnk in pm.links[:10]:
                    lines.append(f"    • {lnk.locator}  [{lnk.name}]")

            if pm.inputs:
                # Show mandatory fields first with [REQUIRED] marker
                required_inputs = [inp for inp in pm.inputs if inp.required]
                optional_inputs = [inp for inp in pm.inputs if not inp.required]
                if required_inputs:
                    lines.append("  ⚠ MANDATORY Form Fields (MUST fill these when creating a record):")
                    for inp in required_inputs[:20]:
                        lines.append(f"    • [REQUIRED] [{inp.locator_type}] {inp.locator}  (tag={inp.tag})")
                if optional_inputs:
                    lines.append("  Optional Form Fields:")
                    for inp in optional_inputs[:15]:
                        lines.append(f"    • [{inp.locator_type}] {inp.locator}  (tag={inp.tag})")
                if not required_inputs and not optional_inputs:
                    lines.append("  Form Inputs:")
                    for inp in pm.inputs[:20]:
                        lines.append(f"    • [{inp.locator_type}] {inp.locator}  (tag={inp.tag})")

            if pm.selects:
                lines.append("  Dropdowns/Selects:")
                for sel in pm.selects[:10]:
                    lines.append(f"    • [{sel.locator_type}] {sel.locator}")

            if pm.testids:
                lines.append(f"  data-testid values: {', '.join(pm.testids[:10])}")

            lines.append("")

        lines.append("=== END OF WEB APP METADATA ===")
        return "\n".join(lines)

    @staticmethod
    def to_structured_json(metadata: WebAppMetadata) -> dict:
        """
        Convert WebAppMetadata to a JSON-serialisable dict for DB storage
        in metadata_normalized.structured_json.
        """
        return {
            "base_url": metadata.base_url,
            "pages": [
                {
                    "url": pm.url,
                    "path": pm.path,
                    "title": pm.title,
                    "headings": pm.headings,
                    "buttons": [vars(e) for e in pm.buttons],
                    "links": [vars(e) for e in pm.links],
                    "inputs": [vars(e) for e in pm.inputs],
                    "selects": [vars(e) for e in pm.selects],
                    "testids": pm.testids,
                }
                for pm in metadata.pages
            ],
        }

    @staticmethod
    def from_structured_json(data: dict) -> WebAppMetadata:
        """Reconstruct WebAppMetadata from a structured_json dict (DB cache hit)."""
        pages = []
        for pd in data.get("pages", []):
            pages.append(
                PageMetadata(
                    url=pd.get("url", ""),
                    path=pd.get("path", ""),
                    title=pd.get("title", ""),
                    headings=pd.get("headings", []),
                    buttons=[ElementInfo(**e) for e in pd.get("buttons", [])],
                    links=[ElementInfo(**e) for e in pd.get("links", [])],
                    inputs=[ElementInfo(**e) for e in pd.get("inputs", [])],
                    selects=[ElementInfo(**e) for e in pd.get("selects", [])],
                    testids=pd.get("testids", []),
                )
            )
        return WebAppMetadata(base_url=data.get("base_url", ""), pages=pages)

    # ── Internal: per-page extraction ───────────────────────────────

    @staticmethod
    async def _visit_page(
        page: Page, url: str, base_url: str
    ) -> Optional[PageMetadata]:
        """Navigate to `url` and extract all useful DOM metadata."""
        try:
            await page.goto(url, wait_until="domcontentloaded", timeout=25_000)
            # Extra wait for SPA hydration (Next.js, React, Vue)
            try:
                await page.wait_for_load_state("networkidle", timeout=5_000)
            except Exception:
                await asyncio.sleep(1)
        except Exception as e:
            logger.warning(f"[CRAWLER] Navigation failed for {url}: {e}")
            return None

        parsed = urlparse(url)
        path = parsed.path or "/"

        pm = PageMetadata(url=url, path=path)

        # Title
        try:
            pm.title = (await page.title()) or ""
        except Exception:
            pass

        # Headings h1-h3
        try:
            headings = await page.evaluate("""() => {
                return [...document.querySelectorAll('h1, h2, h3')]
                    .map(h => h.innerText?.trim())
                    .filter(Boolean)
                    .slice(0, 8);
            }""")
            pm.headings = headings or []
        except Exception:
            pass

        # Buttons
        try:
            buttons_raw = await page.evaluate("""() => {
                const els = [...document.querySelectorAll(
                    'button, [role="button"], input[type="submit"], input[type="button"]'
                )].filter(el => el.offsetParent !== null);
                return els.slice(0, 25).map(el => ({
                    tag: el.tagName.toLowerCase(),
                    text: (el.innerText || el.value || el.getAttribute('aria-label') || '').trim(),
                    ariaLabel: el.getAttribute('aria-label') || '',
                    testid: el.getAttribute('data-testid') || '',
                    type: el.getAttribute('type') || '',
                }));
            }""")
            for raw in (buttons_raw or []):
                name = raw.get("ariaLabel") or raw.get("text") or ""
                if not name:
                    continue
                name = name[:80]
                locator = f"role=button, name={name}"
                pm.buttons.append(ElementInfo(
                    role="button", name=name, tag=raw.get("tag", "button"),
                    locator_type="role", locator=locator,
                ))
                if raw.get("testid"):
                    pm.testids.append(raw["testid"])
        except Exception as e:
            logger.debug(f"[CRAWLER] Button extraction failed: {e}")

        # Links
        try:
            links_raw = await page.evaluate("""(baseUrl) => {
                return [...document.querySelectorAll('a[href]')]
                    .filter(a => a.offsetParent !== null &&
                                 (a.href.startsWith(baseUrl) || a.href.startsWith('/')))
                    .slice(0, 20)
                    .map(a => ({
                        text: (a.innerText || a.getAttribute('aria-label') || '').trim(),
                        href: a.href,
                        ariaLabel: a.getAttribute('aria-label') || '',
                    }));
            }""", base_url)
            for raw in (links_raw or []):
                name = raw.get("ariaLabel") or raw.get("text") or ""
                if not name:
                    continue
                name = name[:80]
                locator = f"role=link, name={name}"
                pm.links.append(ElementInfo(
                    role="link", name=name, tag="a",
                    locator_type="role", locator=locator,
                ))
        except Exception as e:
            logger.debug(f"[CRAWLER] Link extraction failed: {e}")

        # Form inputs
        try:
            inputs_raw = await page.evaluate("""() => {
                return [...document.querySelectorAll(
                    'input:not([type=hidden]):not([type=submit]):not([type=button]):not([type=checkbox]):not([type=radio]),' +
                    'textarea'
                )].filter(el => el.offsetParent !== null)
                  .slice(0, 25)
                  .map(el => {
                    // Find associated <label>
                    let label = '';
                    let labelHasAsterisk = false;
                    if (el.id) {
                        const lbl = document.querySelector('label[for="' + el.id + '"]');
                        if (lbl) {
                            label = lbl.innerText?.trim() || '';
                            // Check if label contains * marker for required
                            labelHasAsterisk = lbl.textContent?.includes('*') || false;
                        }
                    }
                    if (!label) label = el.getAttribute('aria-label') || '';
                    if (!label) label = el.getAttribute('placeholder') || '';
                    if (!label) label = el.getAttribute('name') || '';

                    // Detect mandatory: HTML5 required, aria-required, or * in label
                    const isRequired = el.required
                        || el.hasAttribute('required')
                        || el.getAttribute('aria-required') === 'true'
                        || labelHasAsterisk
                        || (el.closest && el.closest('[required]') !== null);

                    return {
                        tag: el.tagName.toLowerCase(),
                        type: el.getAttribute('type') || 'text',
                        label: label,
                        placeholder: el.getAttribute('placeholder') || '',
                        ariaLabel: el.getAttribute('aria-label') || '',
                        name: el.getAttribute('name') || '',
                        testid: el.getAttribute('data-testid') || '',
                        id: el.id || '',
                        required: isRequired,
                    };
                });
            }""")
            for raw in (inputs_raw or []):
                label = (
                    raw.get("label") or
                    raw.get("ariaLabel") or
                    raw.get("placeholder") or
                    raw.get("name") or ""
                )
                if not label:
                    continue
                label = label[:80]

                # Choose best locator type
                if raw.get("label"):
                    locator_type = "label"
                    locator = label
                elif raw.get("ariaLabel"):
                    locator_type = "label"
                    locator = raw["ariaLabel"][:80]
                elif raw.get("placeholder"):
                    locator_type = "placeholder"
                    locator = raw["placeholder"][:80]
                elif raw.get("testid"):
                    locator_type = "testid"
                    locator = raw["testid"]
                elif raw.get("id"):
                    locator_type = "css"
                    locator = f"#{raw['id']}"
                else:
                    locator_type = "css"
                    locator = f"input[name='{raw.get('name', '')}']"

                pm.inputs.append(ElementInfo(
                    role="textbox", name=label, tag=raw.get("tag", "input"),
                    locator_type=locator_type, locator=locator,
                    required=bool(raw.get("required", False)),
                ))
                if raw.get("testid"):
                    pm.testids.append(raw["testid"])
        except Exception as e:
            logger.debug(f"[CRAWLER] Input extraction failed: {e}")

        # Checkboxes & radios
        try:
            cb_raw = await page.evaluate("""() => {
                return [...document.querySelectorAll('input[type=checkbox], input[type=radio]')]
                    .filter(el => el.offsetParent !== null)
                    .slice(0, 10)
                    .map(el => {
                        let label = el.getAttribute('aria-label') || '';
                        if (!label && el.id) {
                            const lbl = document.querySelector('label[for="' + el.id + '"]');
                            if (lbl) label = lbl.innerText?.trim() || '';
                        }
                        return { label, type: el.getAttribute('type') };
                    });
            }""")
            for raw in (cb_raw or []):
                name = raw.get("label") or ""
                if not name:
                    continue
                pm.inputs.append(ElementInfo(
                    role="checkbox" if raw.get("type") == "checkbox" else "radio",
                    name=name[:80], tag="input",
                    locator_type="label", locator=name[:80],
                ))
        except Exception:
            pass

        # Selects / comboboxes
        try:
            sel_raw = await page.evaluate("""() => {
                return [...document.querySelectorAll('select, [role="combobox"], [role="listbox"]')]
                    .filter(el => el.offsetParent !== null)
                    .slice(0, 10)
                    .map(el => {
                        let label = el.getAttribute('aria-label') || el.getAttribute('name') || '';
                        let labelHasAsterisk = false;
                        if (!label && el.id) {
                            const lbl = document.querySelector('label[for="' + el.id + '"]');
                            if (lbl) {
                                label = lbl.innerText?.trim() || '';
                                labelHasAsterisk = lbl.textContent?.includes('*') || false;
                            }
                        }
                        const isRequired = el.required
                            || el.hasAttribute('required')
                            || el.getAttribute('aria-required') === 'true'
                            || labelHasAsterisk;
                        const options = [...(el.querySelectorAll('option') || [])]
                            .map(o => o.innerText?.trim()).filter(Boolean).slice(0, 5);
                        return { label, options, tag: el.tagName.toLowerCase(), required: isRequired };
                    });
            }""")
            for raw in (sel_raw or []):
                label = raw.get("label") or ""
                if not label:
                    continue
                locator = label[:80]
                options_str = ""
                if raw.get("options"):
                    options_str = f"  options: {', '.join(raw['options'])}"
                pm.selects.append(ElementInfo(
                    role="combobox", name=f"{locator}{options_str}",
                    tag=raw.get("tag", "select"),
                    locator_type="label", locator=locator,
                    required=bool(raw.get("required", False)),
                ))
        except Exception as e:
            logger.debug(f"[CRAWLER] Select extraction failed: {e}")

        # data-testid attributes
        try:
            testids = await page.evaluate("""() => {
                return [...document.querySelectorAll('[data-testid]')]
                    .map(el => el.getAttribute('data-testid'))
                    .filter(Boolean)
                    .slice(0, 20);
            }""")
            for tid in (testids or []):
                if tid not in pm.testids:
                    pm.testids.append(tid)
        except Exception:
            pass

        return pm


# ── Helpers ──────────────────────────────────────────────────────────


async def _make_context(browser, auth_session_path: Optional[str]) -> BrowserContext:
    """Create a browser context, optionally loading a stored session."""
    if auth_session_path and os.path.exists(auth_session_path):
        try:
            ctx = await browser.new_context(storage_state=auth_session_path)
            logger.info(f"[CRAWLER] Loaded auth session from {auth_session_path}")
            return ctx
        except Exception as e:
            logger.warning(f"[CRAWLER] Failed to load session: {e}")
    return await browser.new_context()


def _normalize_url(url: str, base_url: str) -> Optional[str]:
    """
    Normalise a URL:
      - Must be within the same origin as base_url
      - Strip query params and fragments (crawl each path once)
      - Return None if external or non-HTTP
    """
    try:
        base_parsed = urlparse(base_url)
        parsed = urlparse(url)

        # Must be same origin
        if parsed.scheme not in ("http", "https"):
            return None
        if parsed.netloc and parsed.netloc != base_parsed.netloc:
            return None

        # Reconstruct clean URL (no query/fragment)
        clean = f"{base_parsed.scheme}://{base_parsed.netloc}{parsed.path}"
        # Drop trailing slash duplicates
        if clean.endswith("/") and clean != base_url.rstrip("/") + "/":
            clean = clean.rstrip("/")
        return clean
    except Exception:
        return None
