"""add_status_to_test_case

Revision ID: dd3a5323ee4a
Revises: 32acecc08c8b
Create Date: 2026-02-19 11:19:23.407540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3a5323ee4a'
down_revision: Union[str, None] = '32acecc08c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'status')
    # ### end Alembic commands ###
